---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ${{ values.name }}
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: ${{ values.repoUrl }}